---
title: "SPOT_demo"
author: "Luyang Fang"
date: "2024-11-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls())
source("util.R")
```


```{r}
data_1 = simu.X.generate(n=3000, d=2, p.type=2)$X # data from class 1
data_2 = mvrnorm(n = 3000, mu=c(5,5), Sigma=matrix(c(1,0,0,1),ncol=2)) # data from class 2
true_label = c( rep(1,3000), rep(2,3000) )
col = c("azure4", "khaki2", "chartreuse4")[true_label]

data = rbind(data_1, data_2)

# visualization
plot(data, pch=".", col=col, cex=2, 
     cex.axis=1.2, mgp=c(3,0.5,0),
     cex.lab=1.5,
     ann = F)
```

```{r}
### get the index of the selected subset via SPOT:
ind_proposed = SPOT_func(data, d=2, shot=200, true_label=NA, seed=2022, plot=TRUE)
```


```{r}
# if you have the true label and want to have a better visualization, include the true_label
ind_proposed = SPOT_func(data, d=2, shot=200, true_label=true_label, seed=2022, plot=TRUE)
```




```{r}
# without the plot:
ind_proposed = SPOT_func(data, d=2, shot=200, true_label=NA, seed=2022, plot=FALSE)
```




